### ISSUE TITLE
使用 mongodb 之类而不是 sqlite

### ISSUE THREAD

**Issue by z0z0r4** [SaltWood-Studio/Open93AtHome-V3#19]
性能堪忧

**Comment by SALTWOOD** [comment]
有计划，但是文件列表是启动时扫描，不存在数据库里头；数据库里只有 UserEntities 和 ClusterEntities 两个表，分别存储登陆用户数据和节点数据，而且都在内存中存储

低优先级罢

**Comment by SALTWOOD** [comment]
比较闲了，过段时间可能会做（

**Comment by z0z0r4** [comment]
...毫无音讯（

**Comment by SALTWOOD** [comment]
Mongo DB 我没有测试条件，最多做到 MySQL : (
群里发生的事你又不是不知道

**Comment by z0z0r4** [comment]
oo，想起来了...过了一周自动 prune 了
