### ISSUE TITLE
获取链接的时候有 undefined 字眼、无法正常下线和保活时候应传回来的 time 是由节点端的 time，而不是服务端的 time

### ISSUE THREAD

**Issue by tianxiu2b2t** [SaltWood-Studio/Open93AtHome-V3#46]
![ffcd51e9b348e37952a55349044bf4b7](https://github.com/user-attachments/assets/9f71a431-1ee4-4848-a6d6-4f42c8fcb6d9)

**Comment by SALTWOOD** [comment]
outdated，修了 
分别在 [45dd24](https://github.com/SaltWood-Studio/Open93AtHome-V3/commit/45dd24414a5e18a3894dad36a3bb889fa65aaeb1) 和 [a25831](https://github.com/SaltWood-Studio/Open93AtHome-V3/commit/a25831945d3ba6102003b728e169b8548de111c1)

至于无法正常下线，没有日志看不出来
有详细信息可以补充
